### ISSUE TITLE
Explore Custom VPC vs. No VPC Approaches to Vertex Workbench Project

### ISSUE THREAD

**Issue by Collinbrown95** [PHACDataHub/infra-core#23]
# Description

It is not immediately clear which networking approach is the best fit for the Vertex Workbench project. Currently, the two options we are considering are as follows:

1. Custom VPC with peering to a Producer services network, as shown in GCP's [Private Services Access diagram](https://cloud.google.com/vpc/docs/private-services-access#example).
2. No VPC whatsoever (i.e. 100% google-managed networks for the SaaS we use).

To investigate this in more detail, @tcaky is going to create an empty project in which we can try the Custom VPC approach with peering to a Producer Service network and @vedantthapa is going to provision a project with the "No VPC" approach.

We'll update this issue with our findings, and ultimately a decision on which approach to take.

**Comment by vedantthapa** [comment]
@Collinbrown95 
The "No VPC" project space should be up by now as per the spec here: https://github.com/PHACDataHub/infra-core-instances/blob/main/vertexai/vertexai-no-vpc/vertexai.yaml. You have owner permissions on the project.

Please let me know if you face any issues or need changes :)

**Comment by Collinbrown95** [comment]
The project's main use case ended up deprecating vertex workbench in favour of RStudio cloud workstations because Epidemiologists prefer the RStudio environment.
